/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearanceToggle: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/AppearanceToggle.vue')['default']
    AppFooter: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/AppFooter.vue')['default']
    AppSBox: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/AppSBox.vue')['default']
    ArticlesMenu: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/ArticlesMenu.vue')['default']
    CopyrightInfo: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/CopyrightInfo.vue')['default']
    Disclaimer: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/Disclaimer.vue')['default']
    FontSwitcher: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/FontSwitcher/FontSwitcher.vue')['default']
    FontSwitcherItem: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/FontSwitcher/FontSwitcherItem.vue')['default']
    HomeContent: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/HomeContent.vue')['default']
    PageInfo: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/PageInfo.vue')['default']
    ReadingTime: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/ReadingTime.vue')['default']
  }
}

// For TSX support
declare global {
  const AppearanceToggle: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/AppearanceToggle.vue')['default']
  const AppFooter: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/AppFooter.vue')['default']
  const AppSBox: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/AppSBox.vue')['default']
  const ArticlesMenu: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/ArticlesMenu.vue')['default']
  const CopyrightInfo: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/CopyrightInfo.vue')['default']
  const Disclaimer: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/Disclaimer.vue')['default']
  const FontSwitcher: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/FontSwitcher/FontSwitcher.vue')['default']
  const FontSwitcherItem: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/FontSwitcher/FontSwitcherItem.vue')['default']
  const HomeContent: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/HomeContent.vue')['default']
  const PageInfo: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/PageInfo.vue')['default']
  const ReadingTime: typeof import('./../../packages/vitepress-theme-sjtu-wiki/dist/components/ReadingTime.vue')['default']
}